### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by OlgaYubil** [MetalHead89/fsd_part4#1]
Все требования и стандарты распространяются на оба проекта, здесь также надо использовать БЭМ. В компоненте scale не может находиться компонент slider. 

![2021-09-04_22-37-15](https://user-images.githubusercontent.com/82147736/132106917-f276a7f4-5f72-4e41-8a91-d22723e0cdc6.png)

**Comment by MetalHead89** [comment]
Изменены названия компонентов и их вложенность в соответствии с методологией БЭМ
