### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by OlgaYubil** [MetalHead89/fsd_part4#12]
Если тест упадет, сообщение будет не очень информативным. Хорошо бы придумать осмысленный заголовок, а не переносить просто из кода ожидаемые значения.

![2021-09-27_15-22-11](https://user-images.githubusercontent.com/82147736/134914787-bf11e1e3-ebd4-4b26-8d1b-129a16cdaee7.png)

**Comment by MetalHead89** [comment]
Переделаны заголовки тестов
