### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by Azmodan95** [MetalHead89/fsd_part4#16]
Модель нечего не должна знать о виде и не должна производить ни каких расчетов связанных с ним, то есть не должно быть расчетов связанных с шириной, координатами и т.п., она должна оперировать данными относящимися к бизнес логике это максимальный диапазон, текущие значения, размер шага и т.п. А вид как раз должен занимать только расчетами связанными с шириной, координатами и т.п., и соответственно не должно быть расчетов связанных с бизнес логикой. К примеру вид может вычислить процентное соотношение насколько был передвинут бегунок относительно всей ширины слайдера, и это уже значение передавать в модель.

---

https://github.com/MetalHead89/fsd_part4/blob/db57f07f08a1848a60cf801e4cafa0c7d5722e31/src/plugins/simple-js-slider/controller/simple-js-slider-controller.ts#L76
Еще есть странный момент, зачем здесь передавать целый экземпляр контроллера? Это привязывает к определенной структуре, и обсервер получает доступ ко всему экземпляру. Почему просто не передать метод update вместо передачи всего экземпляра? Либо передавать сразу под определенное событие нужный метод. Второй вариант мне кажется будет более читаемым.

**Comment by MetalHead89** [comment]
Полностью переделана архитектура, методы работающие с коорддинатами и размерами перенесены из Model в View. Так же переделан класс Observer, теперь при регистрации можно сразу передавать методы, которые будут реагировать на события
