### ISSUE TITLE
Switch case

### ISSUE THREAD

**Issue by OlgaYubil** [MetalHead89/fsd_part4#5]
Альтернатива if/else и switch: литералы объектов в JavaScript

![2021-09-17_23-17-06](https://user-images.githubusercontent.com/82147736/133851853-f017f142-f8b9-4863-89a6-830d38a99f1f.png)

**Comment by MetalHead89** [comment]
Операторы switch/case и if/else в методах update заменены на конструкции использующие литералы объекта events
