### ISSUE TITLE
demo.ts

### ISSUE THREAD

**Issue by OlgaYubil** [MetalHead89/fsd_part4#7]
demo.ts лучше переписать на класс для единообразия со всем проектом, да и работать с ним будет удобнее.

**Comment by MetalHead89** [comment]
demo.ts переписан на класс

**Comment by OlgaYubil** [comment]
Лучше будет сначала сформировать нужный тебе элемент, и вставлять его в DOM в последнюю очередь. То есть, сначала 
в sliderWrapper вставляешь иконку и кнопку, а уже потом помещаешь в buttonWrapper.

![2021-09-25_16-02-24](https://user-images.githubusercontent.com/82147736/134773714-3877e2de-a5a6-4c24-a335-3843c402dcb8.png)
